# Generated by Django 5.0.6 on 2024-05-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionHub', '0002_alter_question_options_answer_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='author',
        ),
    ]
