# Generated by Django 5.0.6 on 2024-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionHub', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_closed',
            field=models.BooleanField(choices=[(True, 'Закрито'), (False, 'Відкрито')], default=False, verbose_name='Чи закрито'),
        ),
    ]
