# Generated by Django 5.0.6 on 2024-05-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionHub', '0004_question_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
    ]
