# Generated by Django 5.0.6 on 2024-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionHub', '0007_question_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created_at',), 'verbose_name': 'Відповідь', 'verbose_name_plural': 'Відповіді'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-created_at',), 'verbose_name': 'Питання', 'verbose_name_plural': 'Питання'},
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=234, max_length=255, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
