# Generated by Django 5.0.6 on 2024-05-18 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionHub', '0008_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='url'),
        ),
    ]
