# Generated by Django 5.0.6 on 2024-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Чи анонімний голос'),
        ),
    ]
