# Generated by Django 5.0.6 on 2024-05-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-created_at',), 'verbose_name': 'Голосування', 'verbose_name_plural': 'Голосування'},
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='question',
            new_name='text',
        ),
    ]
