# Generated by Django 5.0.6 on 2024-05-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опитування', 'verbose_name_plural': 'Опитування'},
        ),
        migrations.AlterModelOptions(
            name='pollcategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AddField(
            model_name='pollcategory',
            name='name',
            field=models.CharField(default=34, max_length=255),
            preserve_default=False,
        ),
    ]
