# Generated by Django 5.0.6 on 2024-05-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0002_alter_poll_options_alter_pollcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='title',
        ),
    ]
