# Generated by Django 5.0.6 on 2024-05-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0002_alter_poll_options_rename_question_poll_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('-votes',), 'verbose_name': 'Вибір', 'verbose_name_plural': 'Вибори'},
        ),
    ]
