# Generated by Django 5.0.6 on 2024-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0003_alter_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_closed',
            field=models.BooleanField(choices=[(True, 'Закрито'), (False, 'Відкрито')], default=False, verbose_name='Чи закрито'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(choices=[(True, 'Так'), (False, 'ні')], default=False, verbose_name='Чи анонімний голос'),
        ),
    ]
