# Generated by Django 5.0.6 on 2024-05-15 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0004_answer_pollanswer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollAnswer',
        ),
    ]
