# Generated by Django 5.0.6 on 2024-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0004_alter_poll_is_closed_alter_vote_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_anonymous',
            field=models.BooleanField(choices=[(True, 'Так'), (False, 'Ні')], default=False, verbose_name='Чи анонімний голос'),
        ),
    ]
