# Generated by Django 5.0.6 on 2024-05-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
