# Generated by Django 5.0.6 on 2024-05-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0006_poll_is_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голос', 'verbose_name_plural': 'Голоси'},
        ),
    ]
