# Generated by Django 5.0.6 on 2024-05-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollFeed', '0006_useranswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Відповідь користувача', 'verbose_name_plural': 'Відповіді користувачів'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
